### ISSUE TITLE
Ability to specify schema and data without a filename

### ISSUE THREAD

**Issue by simonw** [23andMe/Yamale#104]
Currently you use the library like this:
```python
import yamale
schema = yamale.make_schema('./schema.yaml')

# Create a Data object
data = yamale.make_data('./data.yaml')

# Validate data against the schema. Throws a ValueError if data is invalid.
yamale.validate(schema, data)
```
It would be really useful if there was an option to provide the schema and data as Python strings instead - that way the could be loaded from a database or from an incoming HTTP request.

Something like this could work

```python
import yamale

schema = yamale.make_schema(content="""
name: str()
age: int(max=200)
height: num()
awesome: bool()
""")

data = yamale.make_data(content="""
name: Bill
age: 26
height: 6.2
awesome: True
""")

yamale.validate(schema, data)
```

**Comment by mildebrandt** [comment]
Thanks for your interest in Yamale! We do accept pull requests if someone is up for it. I like the proposed solution, making the first parameter optional to maintain API compatibility.

**Comment by simonw** [comment]
A couple of implementation challenges: first, it has to work with both Python 2 and Python 3. Secondly, it has to take the two possible parsers into account (pyyaml and ruamel).

Both of those parser libraries operate on a stream passed to their `load_all()` method:

https://github.com/23andMe/Yamale/blob/f5444a3602e07871c4700efe6aaf75c51addb384/yamale/readers/yaml_reader.py#L4-L18

So I think the way to do this is rewrite those two functions to accept a file-like object rather than a filepath on disk. Then rewrite this `parse_file()` method to instead take either a filepath or a string of content:

https://github.com/23andMe/Yamale/blob/f5444a3602e07871c4700efe6aaf75c51addb384/yamale/readers/yaml_reader.py#L27-L32

Proposed new signature (renamed to `parse_yaml()` because it doesn't just do files any more):
```python
def parse_yaml(path=None, content=None, parser="pyyaml"):
    assert (path is none and content is not None) or (path is not None and content is None), \
        "Pass either path= or content=, not both"
    ....
```

**Comment by simonw** [comment]
I can add an extra parametrize decorator here to exercise both the `path=` version and the `content=` version:

https://github.com/23andMe/Yamale/blob/f5444a3602e07871c4700efe6aaf75c51addb384/yamale/readers/tests/test_yaml.py#L26-L35

**Comment by simonw** [comment]
I haven't written code that works in Python 2 _and_ Python 3 for ages! Just learned that the `io` module is available in Python 2.7, which helps a lot with writing compatible code.

**Comment by simonw** [comment]
Pull request: https://github.com/23andMe/Yamale/pull/105

**Comment by simonw** [comment]
Updated documentation: https://github.com/23andMe/Yamale/blob/5fdb19376d5f2d9165eaa1a0e85265346e64e39f/README.md#api

<img width="793" alt="Yamale_README_md_at_5fdb19376d5f2d9165eaa1a0e85265346e64e39f_·_23andMe_Yamale" src="https://user-images.githubusercontent.com/9599/85784268-f6544680-b6dc-11ea-98b5-7ea33a238401.png">

**Comment by blopker** [comment]
Hey @simonw, thank you for your contribution. Also, thanks for reminding us we still support Python 2. I've made a ticket to address that for our next major version: https://github.com/23andMe/Yamale/issues/106

**Comment by mildebrandt** [comment]
This enhancement is in version 2.2.0. Thanks!
