### ISSUE TITLE
regex match for [0-9] does not work

### ISSUE THREAD

**Issue by JeanMarieCalmel** [23andMe/Yamale#116]
the following schema shows a bug in the regex validator in Yamale:
**yamale_schema_regex_bug.yaml**
> buggy: regex('[0-9]', name="match for [0-9]???? This is the Bug")
> working: regex ('[0-9]foo')

when submitting the following yaml for validation: 
**yamale_regex_bug_valid_yaml.yaml**
> buggy: 3
> working: 3foo

it fails while it should not (the first line fails while the second succeeds) as shown below:

> $ yamale -s yamale_schema_regex_bug.yaml yamale_regex_bug_valid_yaml.yaml 
> Validating /<path hidden>/yamale_regex_bug_valid_yaml.yaml...
> Validation failed!
> Error validating data '/<path hidden>/yamale_regex_bug_valid_yaml.yaml' with schema 'yamale_schema_regex_bug.yaml'
>         buggy: '3' is not a match for [0-9]???? This is the Bug.

The same Regular Expression works correctly on python 3.8.3 as per the following:
> \>>> import re
> \>>> print(re.search('[0-9]', '3'))
> <re.Match object; span=(0, 1), match='3'>

**Comment by mechie** [comment]
Working as intended, in my opinion. In your example, `buggy: 3` is a yaml integer, not a string.
**schema.yml**
```yaml
a: regex('[0-9]')
b: int(min=0,  max=9)
c: regex ('[0-9]foo')
```
**sample.yml**
```yaml
a: '3'
b: 3
c: 3foo
```
**shell:**
```
$ yamale -s schema.yml text.yml
Validating text.yml...
Validation success!
```
See [the YAML integer page](https://yaml.org/type/int.html) for definition and examples. In short, add single or double quotes around numbers you want interpreted as strings.

**Comment by JeanMarieCalmel** [comment]
Thanks for the quick turnaround.

I see your point, I have been confused by the difference of behavior compared to the same RE directly in Python and yes I had 'worked around' my problem using int(min=1) in replacement of [1-9][0-9]*.

I think we can close this issue, as you properly pointed out, it is working as intended and has a logical explanation.

**Comment by mildebrandt** [comment]
Thanks @mechie !
