### ISSUE TITLE
support for home brew version on mac 

### ISSUE THREAD

**Issue by chukka** [23andMe/Yamale#123]
Hi Team,

Is there any plan to support homebrew support  on mac - `brew install yamale`

Thanks

**Comment by mildebrandt** [comment]
Hi, thanks for your interest in Yamale. 

Supporting homebrew isn't something that we're willing to take on at this time. Thanks for the suggestion though!

**Comment by PeterWhittaker** [comment]
Installation on my Mac was as easy as:
1. brew install python3
2. pip3 install yamale

Perhaps a documentation update? Hmm, let me look into that....
