### ISSUE TITLE
[Enhancement] : "union-like" collection to enforce one of an "all-optional" set

### ISSUE THREAD

**Issue by PeterWhittaker** [23andMe/Yamale#124]
I am using Yamale to define schema for a linear pipeline; [refer to this example](https://github.com/PeterWhittaker/SELinuxLinearAssuredPipeline/blob/master/_schema.yml): Essentially, every pipeline consists of an entry, zero or more filters, and an exit.

The *entry" element can be one of two things:
 - a *receiver*, that listens for connection requests, or
 - a *getter*, that reaches out data

My definition of entry is
```
entry: # one of these is required, how to enforce?
  custom: include('receiver', required=False)
  custom: include('getter', required=False))
```
My enhancement request is to have a way of specifying that *entry* must have one and exactly one of those potential values. For example,

```entry: union(include('receiver'), include('getter'))```

I would use that same technique to force each *process* to be one and only one of the all-optional elements defined therein (refer to the same URL, above).

Thoughts?

**Comment by blopker** [comment]
Apologies if I've overlooked some of the nuance to this question, but does the `any` validator work for you?

**Comment by PeterWhittaker** [comment]
> Apologies if I've overlooked some of the nuance to this question, but does the `any` validator work for you?

I cannot believe I missed that: I have had [the main page](https://github.com/23andMe/Yamale) open for days and simply overlooked it. Thank you, @blopker! I'll close this.

**Comment by blopker** [comment]
No problem! Glad to help. Is there some keyword or phrase we can add to the docs that would have made it easier to find? I've seen other people miss `any` in the docs as well.

**Comment by PeterWhittaker** [comment]
> No problem! Glad to help. Is there some keyword or phrase we can add to the docs that would have made it easier to find? I've seen other people miss `any` in the docs as well.

I started answering this and decided [a pull request was just as easy](https://github.com/23andMe/Yamale/pull/126).
