### ISSUE TITLE
Validating unamed list

### ISSUE THREAD

**Issue by goodwillcoding** [23andMe/Yamale#13]
Esteemed maintainer,

I am not sure how one would validate an unamed list:of maps
- id: 1
- id: 2

**Comment by blopker** [comment]
Hey! Thanks for using Yamale. 

I think you're pointing out one of the current limitations though. Yamale assumes the top-level data structure is a map/dictionary. so currently there is no way to validate a file that is a list.

Ex:
```yaml
- id: 1
- id: 2
```

However, you can either give the list a name or separate each map in to its own file. On the other hand we are accepting pull requests and would love your input.

Cheers!

**Comment by mildebrandt** [comment]
There has been no additional interest in this feature. I'll close for now and revisit if there's more interest.
