### ISSUE TITLE
A "schema.yml file not found" message would be nice

### ISSUE THREAD

**Issue by matthewdeanmartin** [23andMe/Yamale#131]
I'm using git-bash on windows 10. For yamale installed with pipx or pipenv, if I run

`yamale somefile.yml` it blows up with

```
 File "c:\users\matth\appdata\local\programs\python\python38\lib\ntpath.py", line 186, in split
    seps = _get_bothseps(p)
  File "c:\users\matth\appdata\local\programs\python\python38\lib\ntpath.py", line 35, in _get_bothseps
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object
Validating C:\Users\matth\public_record\python_base_image\.gitlab-ci.yml...
```

When a schema.yaml file exists, I do not get the unhelpful error message, which implies that there is a problem with the OS, file system or venv, instead of just saying "Can't find a schema.yaml file"

**Comment by mildebrandt** [comment]
Part of release 3.0.3
