### ISSUE TITLE
"map" validator gets confused when keys are duplicated

### ISSUE THREAD

**Issue by ivocavalcante** [23andMe/Yamale#134]
Consider schema and data below:

**schema.yaml**
```
maptest: map(bool())
```

**test.yaml**
```
maptest: 
  key1: false 
  key2: xpto 
  key2: true 
```

**Expected behavior: (either one of)**
- If YAML grammar doesn't allow for duplicate keys on above situation (and this I honestly don't know) Yamale should complain and fail validation.
- If duplicated keys are allowed, then Yamale should validate both, which means failing on the first "key2". What happens instead, is that it ignores the first "key2" and validates the second, resulting in a succesfsull validation (which is incorrect).

Teste on latest release, 3.0.2. Any more info, just ask.

**Comment by mildebrandt** [comment]
Hi, thanks for using Yamale. 

This behavior is dependent on the parser used; we don't take a stance on whether the file is syntactically valid YAML. The returned object from a `yaml.load()` is what Yamale validates. Here a discussion in the PyYAML project that covers this case: https://github.com/yaml/pyyaml/issues/165

The ruamel parser will fail to load a document with duplicate keys. To use ruamel with Yamale, you can use the `--parser ruamel` option on the command line: https://github.com/23andMe/Yamale#command-line

**Comment by ivocavalcante** [comment]
Thanks for explaining, I'll do as suggested.
