### ISSUE TITLE
Verifying file with multiple documents of different types

### ISSUE THREAD

**Issue by shaunc** [23andMe/Yamale#139]
Thanks for Yamale!

Have used for a few projects already, but now have a problem. I have a file with several yaml documents, of differing types.
```
kind: foo
# ... more content corresponding to type foo
---
kind: bar
# ... more content corresponding to type bar
---
...
```
[Although they aren't, one could picture them as kubernetes manifests, for instance.]

Depending on the `kind` parameter, I want to validate each document against one of several schemas. How can I best accomplish this with Yamale?

**Comment by mildebrandt** [comment]
Thanks for using Yamale! Here's something that should work for you:
```
any(include('foo'), include('bar'))
---
foo:
  kind: regex('foo')
  foo_stuff: str()
---
bar:
  kind: regex('bar')
  bar_stuff: str()
```

**Comment by shaunc** [comment]
Great -- thanks!

One problem, though, is that I have trouble even reading a multiple document stream. Is there a work-around to open one?
```
In [4]: Y.make_data(content=''' 
   ...: kind: bar 
   ...: -- 
   ...: kind: baz 
   ...: ''' 
   ...: )                                                                                                                                                       
---------------------------------------------------------------------------
ScannerError                              Traceback (most recent call last)
<ipython-input-4-8ef015aa64ab> in <module>
----> 1 Y.make_data(content='''
      2 kind: bar
      3 --
      4 kind: baz
      5 '''

~/Library/Caches/pypoetry/virtualenvs/antegraph-oFhjME_H-py3.8/lib/python3.8/site-packages/yamale/yamale.py in make_data(path, parser, content)
     27 def make_data(path=None, parser='PyYAML', content=None):
     28     from . import readers
---> 29     raw_data = readers.parse_yaml(path, parser, content=content)
     30     if len(raw_data) == 0:
     31         return [({}, path)]

~/Library/Caches/pypoetry/virtualenvs/antegraph-oFhjME_H-py3.8/lib/python3.8/site-packages/yamale/readers/yaml_reader.py in parse_yaml(path, parser, content)
     35             return parse(f)
     36     else:
---> 37         return parse(StringIO(content))

~/Library/Caches/pypoetry/virtualenvs/antegraph-oFhjME_H-py3.8/lib/python3.8/site-packages/yamale/readers/yaml_reader.py in _pyyaml(f)
      9     except AttributeError:  # System does not have libyaml
     10         Loader = yaml.SafeLoader
---> 11     return list(yaml.load_all(f, Loader=Loader))
     12 
     13 

~/Library/Caches/pypoetry/virtualenvs/antegraph-oFhjME_H-py3.8/lib/python3.8/site-packages/yaml/__init__.py in load_all(stream, Loader)
    128     try:
    129         while loader.check_data():
--> 130             yield loader.get_data()
    131     finally:
    132         loader.dispose()

~/Library/Caches/pypoetry/virtualenvs/antegraph-oFhjME_H-py3.8/lib/python3.8/site-packages/yaml/constructor.py in get_data(self)
     43         # Construct and return the next document.
     44         if self.check_node():
---> 45             return self.construct_document(self.get_node())
     46 
     47     def get_single_data(self):

ext/_yaml.pyx in _yaml.CParser.get_node()

ext/_yaml.pyx in _yaml.CParser._compose_document()

ext/_yaml.pyx in _yaml.CParser._compose_node()

ext/_yaml.pyx in _yaml.CParser._compose_mapping_node()

ext/_yaml.pyx in _yaml.CParser._parse_next_event()

ScannerError: while scanning a simple key
  in "<file>", line 3, column 1
could not find expected ':'
  in "<file>", line 4, column 1
```

**Comment by shaunc** [comment]
Another issue even with a single document with alternate types is the errors when it doesn't validate. For instance:
```
>>> schema = yamale.make_schema(content=''' 
any(include('foo'),include('bar')) 
--- 
foo: 
  kind: regex('foo') 
  foo: regex('foo') 
bar: 
  kind: regex('bar') 
  bar: regex('bar') 
''')
>>> data = yamale.make_data(content='kind: foo')
>>> yamale.validate(schema, data)
YamaleError: Error validating data
	foo: Required field missing
	kind: 'foo' is not a regex match.
	bar: Required field missing
```
So if I have several complex types, I'll get the list of errors from trying to match all the types, rather than just errors for the type selected by `kind`. Errors like that aren't going to be very helpful to report back to the user.

**Comment by mildebrandt** [comment]
In your multi-doc string, you need to use three dashes to separate documents. 

The other is a bug which is covered here: https://github.com/23andMe/Yamale/issues/137

**Comment by shaunc** [comment]
Thanks! ... I guess I'll close this -- though the "final" (or "guard") idea might be useful in the context of that other bug. I can copy it over (and mutate appropriately) if you'd like.

**Comment by mildebrandt** [comment]
Thanks for the suggestion. I wouldn't want users to be required to add a a parameter to the validator just to have errors behave as they should. We can fix it without the need for a `final` parameter.

**Comment by shaunc** [comment]
Hmm... but how do you know what errors to issue with:
```
any(include('foo'), include('bar'))
---
foo:
  foo: regex('foo')
  a: str
bar:
  bar: regex('bar')
  b: str
```
For the three erroneous inputs:

1. `{'foo': 'foo', b: 'ok'}`
2. `{'bar': 'bar': a: 'ok'}`
3. `{'a': 'ok', b: 'ok'}`

Intuitively, if we know that `foo` and `bar` select for the "sub-type" then we could flag the first two as matching their respective types and the third as not matching any. But without any user indication seems hard to say wether 1 was a object of type 1 with a bad 'b' or an object of type 2 with missing 'foo' ... and so forth.

**Comment by mildebrandt** [comment]
That is interesting. I think we still need to be clearer in our error reporting when a user wouldn't use  `final`. Can you please open a separate issue for the `final` parameter, and we'll mark it as an enhancement request to continue the discussion there. Thanks!
