### ISSUE TITLE
Collaborate with pre-commit

### ISSUE THREAD

**Issue by k-ogawa-1988** [23andMe/Yamale#163]
I have created a pre-commit hooks for this.

Can I suggest integrating Yamale?

https://github.com/pre-commit/pre-commit.com/pull/515

**Comment by mildebrandt** [comment]
Hi, thank you for your interest in Yamale!

We don't have the bandwidth to help maintain any integration with third-party tools. While we don't mind if you integrate Yamale into other projects, understand that future major releases could break functionality. Always pin to the major release, we try not to introduce breaking changes within a major release. Let me know if you have any questions.

**Comment by k-ogawa-1988** [comment]
@mildebrandt Sure, understood!
Thank you.
