### ISSUE TITLE
Sample of multi-line YAML

### ISSUE THREAD

**Issue by patcon** [23andMe/Yamale#17]
Yes, it's a yaml thing, but users who don't know the YAML spec very well might appreciate a heads-up (by way of example) that this is OK :)

https://github.com/mission-impossible-android/mission-impossible-android/blob/feature/yaml-spec/docs/schema.yaml#L11-L18

```
apps: >
  list(
    str(),
    include('app_fdroid_latest'),
    include('app_fdroid_version'),
    include('app_fdroid_versioncode'),
    include('app_direct_download'),
  )
```

**Comment by blopker** [comment]
Hm, that is a handy technique. However YAML has a ton of features that will also be compatible with Yamale. I'm not sure I want to re-document them in the README here. 

That being said, I think having a link to the spec would be nice.
