### ISSUE TITLE
Feature Request: Schema persistance/dump

### ISSUE THREAD

**Issue by brunocek** [23andMe/Yamale#174]
Hello.

Well done! Great project! Very useful.

I would like to be able to change a Schema programmatically and then persist it back to a file. May we please have a method to persist Schemas (dump into a file/stream)?

Thank you!
Bruno

**Comment by mildebrandt** [comment]
Hi @brunocek , thanks for using Yamale!

Unfortunately, this use case falls outside of what we'd want to support in this library. If you'd like to write this yourself outside of Yamale, please reach out with any questions you have along the way.
