### ISSUE TITLE
Schema included in other schemas

### ISSUE THREAD

**Issue by Chumachenko** [23andMe/Yamale#186]
Hello. I have a question about Yamale validator. Mai i create a one general validation schema.yaml and use than in in another schemas? Should i use schema.add_include(dict) ? 

Thanks in advance

**Comment by Chumachenko** [comment]
**For example:**
 
**_schema1.yml_**

- name: str ()
- sname: str()
- adress: str ()

**_schema2.yml_**

- name: str ()
- sname: str()
- adress: str ()
- phone: num()

Mai i use schema.add_include(dict) in the schema2.yml included config1.yml file?
I mean e.g
schema2.yml

schema.add_include(path/schema1)
- phone: num()

**Comment by mildebrandt** [comment]
Hi, thanks for using Yamale.

The `add_include()` API only takes a Python `dict`, so you'll first need to load the yaml and then pass the resulting `dict` into that method. However, that's only possible when validating using the Python API. Yamale doesn't provide a way to specify this from within a schema file.

**Comment by Chumachenko** [comment]
Thanks
