### ISSUE TITLE
Github release is not up to date with actual release

### ISSUE THREAD

**Issue by corneliusroemer** [23andMe/Yamale#203]
I've noticed a mismatch between the Github release displayed on the front page of this repo and the actual version that Yamale is on.

Github shows 4.0.2 but you're actually at 4.0.4

Would be nice to bring the Github releases up to date @mildebrandt 

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/25161793/184629496-e80fc3ad-a306-41ce-b25b-8762dd9b3758.png">

**Comment by mildebrandt** [comment]
I didn't realize people actually look at that. :) Thanks for bringing it up and we'll try to keep that updated in the future.
