### ISSUE TITLE
Yamale command line treats pipes as directories

### ISSUE THREAD

**Issue by ajuniper** [23andMe/Yamale#254]
If I use a shell process substitution like this:
```
yamale schema.yaml <( process_which_outputs_yaml_to_validate )
```
or
```
command pipeline | yamale schema.yaml /dev/stdin
```

then validation fails because yamale receives the `PATH` argument as e.g. `/dev/fd/63` which fails the `os.path.isfile` test at command_line.py line 103, and is therefore treated as a directory.

Switching line 103 to be `if not os.path.isdir(root):` means it behaves correctly.

**Comment by cblakkan** [comment]
Fixed in #251
