### ISSUE TITLE
Any plan to add regular expression or pattern validation?

### ISSUE THREAD

**Issue by manishabardiya** [23andMe/Yamale#40]
Hi,
Do you have any plan to add regular expression or pattern validation?

Thanks,
Manisha

**Comment by blopker** [comment]
Hey @manishabardiya, I don't have much time for anything but bug fixes these days. However, if you'd like to make a PR I'll take a look.

**Comment by manishabardiya** [comment]
Sure. I will connect you on that.

By the way, with current implementation of Yamale how do you handle such data yaml?
---
"demo1":
    layer:    "1" 
    dir: "/etc/abc"
...

where, demo1 is a token value, it can be anything so we don't have fixed key here. how do you handle such yaml with schema? Can you suggest?

Thanks,
Manisha

**Comment by blopker** [comment]
Man, sorry I missed your question. There's currently no way to handle that. In my experience dynamic keys tend to be an anti-patterns. Many tools do not support it.

**Comment by mildebrandt** [comment]
It seems the original issue has been fixed. If there is additional need or interest for validating dynamic keys, please open a separate issue and we can discuss further. Thanks!
