### ISSUE TITLE
working on a windows OS 

### ISSUE THREAD

**Issue by itamarlev** [23andMe/Yamale#41]
hi,

is there a way to run YAMALE on windows?
I tried it but it did not work.

Thanks,
Itamar

**Comment by blopker** [comment]
If you're still interested, I'd need to see what the error was.

**Comment by itamarlev** [comment]
thanks but I'm no longer working on YAMALE. 
If no one else experienced the same problem, then I guess, the issue is closed.
thanks,
Itamar
