### ISSUE TITLE
What versions of Python 3 should be supported?

### ISSUE THREAD

**Issue by johnthagen** [23andMe/Yamale#43]
README and setup.py state Python 3.4+ but only 3.6 is tested on Travis. Is 3.4 supposed to be supported? Would you accept a PR to add 3.4 and 3.5 testing to Travis CI build?

**Comment by blopker** [comment]
Hey @johnthagen, are you using 3.4 and finding that Yamale is not working?

**Comment by johnthagen** [comment]
More just wondering if it was intentional Travis wasn't testing it to check regressions in 3.4/3.5.

**Comment by blopker** [comment]
OK, I fixed the README. Thanks!
