### ISSUE TITLE
IP and MAC type validation

### ISSUE THREAD

**Issue by ryanmerolle** [23andMe/Yamale#45]
I think leveraging the netaddress module for IP and MAC address validation would be useful.  I get that you do not have time for anything but bugs, so I figured I post this feature request and possibly get to it when I have time myself.  Maybe even someone else might want to take a stab at this  as well.

**Comment by blopker** [comment]
Hey @ryanmerolle, I like the idea, but yes, time is limited!

I'm happy for field a PR, but if you need this functionality, Yamale allows you to write your own validators without pushing upstream. I'll leave this open for now though. Thanks!

**Comment by ryanmerolle** [comment]
Closed by #49
