### ISSUE TITLE
empty yml to validate not detected

### ISSUE THREAD

**Issue by mancusoa74** [23andMe/Yamale#54]
hello,
assume the simple block of code below (may be not a bug)

    schema = yamale.make_schema('schema.yml')
    cfg = yamale.make_data('config.yml')

    try:
        yamale.validate(schema, cfg)
    except ValueError as e:
        log.critical(e)
        sys.exit(1)

where: 
schema.yml is the yaml schema used to validate a config.yml file

Now let's assume in the schema.yml there a line like:
log_file: str(required=True)

Now if I provide an empty config.yml file, the validation succeed with no exception.
So in this way any config.yml is considered valid.

I think would make sense to add a simple check to a non-empty yml file to validate.

if you think this make sense, let me know if you will accept a pull request for it. I can help to fix it.

The tool is great and I enjoy it

thnx
Antonio

**Comment by mildebrandt** [comment]
Hi Antonio, thanks for using Yamale!

We would love to see a PR for this issue. When writing the PR, consider a schema with all optional fields. In this case, an empty file would still be valid. If you can include tests for empty fields that have required fields and all optional fields along with the code, that would be great!

Please let me know if you have any questions. Thanks!

**Comment by abourree** [comment]
Base on [issue #79](https://github.com/23andMe/Yamale/issues/79) analyze, Yamale is not able to complain on empty data: yamale.validate loop on data entries, if there are not, it just return data without any more analysis.
```python
def validate(schema, data, strict=False):
    for d, path in data:
        schema.validate(d, path, strict)
    return data
```
