### ISSUE TITLE
Calling Custom Validator using Yamale commandline

### ISSUE THREAD

**Issue by HemantJoshi11** [23andMe/Yamale#57]
Hi,

I understood that Custom validators can be written. We can call custom validator with python command. 
Is there a way so that we can use custom validator directly with Yamale command (yamale --schema <file_schema> <src file> ).

Regards
Hemant

**Comment by mildebrandt** [comment]
There isn't a great way to do this today. Due to the age of this issue, I'll close it for now. If there's continued interest, please reopen. Thanks!
