### ISSUE TITLE
Cleaner command line error output

### ISSUE THREAD

**Issue by televi** [23andMe/Yamale#64]
Currently, when yamale is used from the command line and an error is found the output is difficult to parse since schema.validate() will raise and then command_line.main() will also raise.  The raise() from command_line.main() doesn't actually add anything new and the raise() from validate() includes the python stack it makes it hard to find the actual problem - I'm only really interested in what yamale found, not the methods it called to find them.

To deal with this locally, I made some very simple changes that I'd be happy to contribute back if you're interested.  In command_line.main(), I simply wrapped the call to _router():
```python
try:
    _router(args.path, args.schema, args.cpu_num, args.parser, args.strict)
except ValueError:
    # Already processed
    pass
else:
    print('Validation success! 👍')
```
To get rid of the python stack from the output, I changed one line in command_line._validate() from
```error += traceback.format_exc()``` to ```error += str(e)```.

With those changes, I was able to change this output
```
Validating /Users/televi/foo.yaml...

Error!
Schema: bar.yaml
Data file: /Users/televi/foo.yaml
Traceback (most recent call last):
  File "/Users/televi/.venv/lib/python3.6/site-packages/yamale/command_line.py", line 29, in _validate
    yamale.validate(schema, data, strict)
  File "/Users/televi/.venv/lib/python3.6/site-packages/yamale/yamale.py", line 38, in validate
    schema.validate(d, path, strict)
  File "/Users/televi/.venv/lib/python3.6/site-packages/yamale/schema/schema.py", line 65, in validate
    raise ValueError(error_str)
ValueError:
Error validating data /Users/televi/foo.yaml with schema bar.yaml
	borg: 'None' is not a str.

Traceback (most recent call last):
  File "/Users/televi/.venv/lib/python3.6/site-packages/yamale/command_line.py", line 29, in _validate
    yamale.validate(schema, data, strict)
  File "/Users/televi/.venv/lib/python3.6/site-packages/yamale/yamale.py", line 38, in validate
    schema.validate(d, path, strict)
  File "/Users/televi/.venv/lib/python3.6/site-packages/yamale/schema/schema.py", line 65, in validate
    raise ValueError(error_str)
ValueError:
Error validating data /Users/televi/foo.yaml with schema bar.yaml
	borg: 'None' is not a str.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/televi/.venv/bin/yamale", line 11, in <module>
    load_entry_point('yamale==2.0', 'console_scripts', 'yamale')()
  File "/Users/televi/.venv/lib/python3.6/site-packages/yamale/command_line.py", line 115, in main
    _router(args.path, args.schema, args.cpu_num, args.parser, args.strict)
  File "/Users/televi/.venv/lib/python3.6/site-packages/yamale/command_line.py", line 97, in _router
    _validate_single(root, schema_name, parser, strict)
  File "/Users/televi/.venv/lib/python3.6/site-packages/yamale/command_line.py", line 68, in _validate_single
    _validate(s, yaml_path, parser, strict)
  File "/Users/televi/.venv/lib/python3.6/site-packages/yamale/command_line.py", line 36, in _validate
    raise ValueError('Validation failed!')
ValueError: Validation failed!
```
to this output
```
Validating /Users/televi/foo.yaml...

Error!
Schema: bar.yaml
Data file: /Users/televi/foo.yaml

Error validating data /Users/televi/foo.yaml with schema bar.yaml
	borg: 'None' is not a str.
```

**Comment by mildebrandt** [comment]
Hi, thanks for using Yamale. I think those proposed changes are fine. I'm a little concerned why `ValueError` exceptions are being passed, can you explain that? In any case, we'd love a PR for this. Thanks!

**Comment by televi** [comment]
Currently, _validate() will detect an error in a try/except block, so when you find an error you’re already doing exception processing.  That block already nicely reports what the problem is and then raises a new exception.  In the current output, thats why you see “During the handling of...”.

Since you already handled that error, you don’t need to handle it again.  In a perfect world it may be nice to raise something other than ValueError but that breaks backwards compatibility.  In any case, since the exception was already handled at the point it occurred there’s no reason handle it again now as we aren’t adding anything of value, hence the pass but only on the specific exception that was handled.

**Comment by televi** [comment]
In looking a bit more it may be useful to print an error in _validate_singleton() when the file isn’t found - else we may bury that error by mistake.

**Comment by abourree** [comment]
I made the same finding: output is ugly when validation fails

I'd like to removed unnecessary exception and return list of errors up to yamale.validation() which is better for an API than printing out and throwing exception.

command_line.py is the one who should output readable errors and exit with non zero status.

The only one exception I think we should kept is when files are not found.

If you are OK, I can push PR on.

**Comment by mildebrandt** [comment]
I agree, thanks!
