### ISSUE TITLE
Add support for 'rec' core type

### ISSUE THREAD

**Issue by slw07g** [23andMe/Yamale#77]
Please add support for the `rec` core type.

**Comment by mildebrandt** [comment]
Thanks for your interest in Yamale. I don't know exactly what you mean by the "rec" type. The only reference I could find is from the Rx tool: http://rx.codesimply.com/coretypes.html

If that's what you're referring to, Yamale already supports this in the schema itself using the `include` validator: https://github.com/23andMe/Yamale#includes

If you want something else, please post an example of the yaml and the suggested schema and we'll see if there's a solution.
