### ISSUE TITLE
feature suggestions

### ISSUE THREAD

**Issue by q10** [23andMe/Yamale#8]
Hello:

If possible, please add the following features to yamale:

1) Unions.  Usage should look like this:

key: union(int(), include('my_type'), string(), ... )

2) min/max length specifications in list()

3) An exclude=True option in map() so that keys that are not in the required or optional keyset of the schema will be rejected

4) Schema Extensions/Merges - this is different from includes in that it does not add an included schema as a _subschema_, but _extends_ a current schema.  For example:

Foo:
   a: int()
   b: str()
   d: list(str())
Bar(Foo):
   b: map()
   c: num()

Bar's full schema when Foo is resolved will be (b is overriden in Bar)

Bar(Foo):
   a: int()
   d: list(str())
   b: map()
   c: num()

**Comment by manishabardiya** [comment]
Do you have any plan to add regular expression or patterns validations?

**Comment by blopker** [comment]
This was merged a while back.
