### ISSUE TITLE
Custom validators require `eval`

### ISSUE THREAD

**Issue by McCroden** [23andMe/Yamale#88]
Version: 2.0.1
OS: Windows 10
Python: 3.8.1

I was having issues making a [Custom Validator](https://github.com/23andMe/Yamale#custom-validators). I tried to implement the Date example and noticed that the error was a string. This was the important part of the error:

```
date: 'datetime.date(2020,3,20)' is not a date.
```

When I used `eval` it worked correctly. Such as:

```python
class Date(Validator):
    # ...
    
    def _is_valid(self, value):
        #  here
        return isinstance(eval(value), datetime.date)
```

**I can make a PR to update the docs.  But, is this (using `eval`) the intended behavior?**

Other than `eval`, the user could instead extract the components of and apply them. 

```python
class Date(Validator):
    # ...
    
    def _is_valid(self, value):
        val = value.replace('datetime.date(', '').replace(')', '').split(',')
        return isinstance(datetime.date(val[0], val[1], val[2]), datetime.date)
```

**Comment by mildebrandt** [comment]
Hi, thanks for using Yamale! 

Can you provide the schema file, data file, and actual code you're testing with? 

Here's mine that works on MacOS 10.14.6, Python 3.7.6, Yamale 2.0.1:

schema.yaml:
```yaml
start_time: include('date_validator')
---
date_validator: date()
```

data.yaml:
```yaml
start_time: 2020-03-23
```

test.py:
```python
import yamale
import datetime
from yamale.validators import DefaultValidators, Validator

class Date(Validator):
    """ Custom Date validator """
    tag = 'date'
    def _is_valid(self, value):
        return isinstance(value, datetime.date)

validators = DefaultValidators.copy()  # This is a dictionary
validators[Date.tag] = Date
schema = yamale.make_schema('./schema.yaml', validators=validators)
data = yamale.make_data('./data.yaml')
yamale.validate(schema, data)
```

**Comment by McCroden** [comment]
Apologies.

schema.yaml

```yaml
start_time: include('date_validator')
---
date_validator: date()
```
**I assumed the date needed to be used as it would in python.**

data.yaml

```yaml
start_time: date(2020,3,23)
```
test.py

```python
import yamale
import datetime
from yamale.validators import DefaultValidators, Validator

class Date(Validator):
    """ Custom Date validator """
    tag = 'date'
    def _is_valid(self, value):
        return isinstance(value, datetime.date)

validators = DefaultValidators.copy()  # This is a dictionary
validators[Date.tag] = Date
schema = yamale.make_schema('./schema.yaml', validators=validators)
data = yamale.make_data('./data.yaml')
yamale.validate(schema, data)
```

### My custom class

Here is the custom class I need. It's using [python-ranges](https://github.com/Superbird11/ranges). This works

schema_range.yaml

```yaml
start_range: include('range_validator')
---
range_validator: Range()
```

data_range.yaml
```yaml
start_range: Range(1,20)
```
This works fine. 

test_range.py

```python
import yamale
from yamale.validators import DefaultValidators, Validator
from ranges import Range

class Rng(Validator):
    """ Custom validator """
    tag = 'Range'

    def _is_valid(self, value):
        return isinstance(eval(value), Range)

validators = DefaultValidators.copy()  # This is a dictionary
validators[Rng.tag] = Rng
schema = yamale.make_schema('./schema_range2.yaml', validators=validators)
data = yamale.make_data('./data_range.yaml')
yamale.validate(schema, data)
```

I have to use `eval`. If I didn't , I'd get this error:

```python
Traceback (most recent call last):
  File "test_range.py", line 19, in <module>
    yamale.validate(schema, data)
  File "/home/stuart/code/learn/sandbox/venv/lib/python3.8/site-packages/yamale/yamale.py", line 38, in validate
    schema.validate(d, path, strict)
  File "/home/stuart/code/learn/sandbox/venv/lib/python3.8/site-packages/yamale/schema/schema.py", line 65, in validate
    raise ValueError(error_str)
ValueError:
Error validating data ./data_range.yaml with schema ./schema_range2.yaml
        start_range: 'Range(1,20)' is not a Range.
```

How is it that for the `date` example, it works with a string in `data.yaml` (i.e. `start_time: 2020-03-23`). ? `datetime.date()` doesn't accept a string as a parameter. I haven't dug deep into yamale to understand how it's handling that. Using the same idea I tried using `start_range: 1,20` in `data_range.yaml`, but that did not work.

Is using `eval` the best approach for me with my custom validator? Thanks.

**Comment by mildebrandt** [comment]
In yaml, timestamp is an actual type: https://yaml.org/type/timestamp.html 

So when the yaml parser reads in the file, it converts `2020-03-23` into a Python `datetime` object. 

Yaml doesn't know about Python objects like `Range()`. I'd avoid using yaml like this, and I'd caution against using `eval` anywhere in your code....but especially in a place that processes user-provided strings that aren't cleaned before running the eval. You don't want the string coming in to end up being something like: `"__import__('os').system('rm -rf /')"`

Instead, I would suggest using a string for the range, like `"1-20"`, and parse that in your validator. Or use the built-in regex validator.

**Comment by McCroden** [comment]
Ok. Thank you, @mildebrandt, for the explanation.
