### ISSUE TITLE
Python validation versions

### ISSUE THREAD

**Issue by abourree** [23andMe/Yamale#98]
In README, we said that Yamale is validated with Python 2.7 and 3.4.
Before PR #81, tox.ini said Python 2.7 and 3.6
Since PR #81, tox.ini said Pythng 2.7 and lastest Python 3

Do we need to validate Yamale on Python 3 older than latest ?
If yes, should we validate from 3.4 to latest ? Or only 3.4 and latest ? Or only 3.4 ?

**Comment by mildebrandt** [comment]
Ah, thanks for catching that. I think going back to python 3.6 would be good and updating the README to reflect that.

**Comment by mildebrandt** [comment]
Thanks! We've decided to drop Python 2.7 support and will be including this change into #107 .
